/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.view;

import br.inatel.dao.PacienteDAO;
import br.inatel.model.Paciente;
import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dvrib
 */
public class PacienteView extends javax.swing.JFrame {

    /**
     * Creates new form PacienteView
     */
    public PacienteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_pacientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tf_cpf = new javax.swing.JTextField();
        tf_paciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_idade = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        l_background = new javax.swing.JLabel();

        jMenu1.setText("Cadastros");

        jMenuItem1.setText("Pacientes");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Médicos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Enfermeiros");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab_pacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_pacientes.setEnabled(false);
        tab_pacientes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tab_pacientesComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tab_pacientes);
        // Populando tabela
        Object nomeColunas[] = {"CPF", "Paciente", "Idade"};
        DefaultTableModel model = new DefaultTableModel(nomeColunas, 0);
        PacienteDAO pacientedao = new PacienteDAO();
        for(Paciente p: pacientedao.getPacientes()) {
            Object rowData[] = {p.getCpf(), p.getNome(), p.getIdade()};
            model.addRow(rowData);
        }
        tab_pacientes.setModel(model);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 350, 250));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CPF:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        tf_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cpfActionPerformed(evt);
            }
        });
        jPanel1.add(tf_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 340, -1));

        tf_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pacienteActionPerformed(evt);
            }
        });
        jPanel1.add(tf_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 340, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome do Paciente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Idade:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, 20));

        tf_idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idadeActionPerformed(evt);
            }
        });
        jPanel1.add(tf_idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 340, -1));

        btn_add.setText("Adicionar");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, -1, -1));

        btn_excluir.setText("Excluír Registro");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 150, -1));

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 230, 90, -1));

        l_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/images/tela.jpg"))); // NOI18N
        jPanel1.add(l_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab_pacientesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tab_pacientesComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_pacientesComponentShown

    private void tf_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cpfActionPerformed

    private void tf_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pacienteActionPerformed

    private void tf_idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idadeActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        Paciente paciente = new Paciente();
        if ("".equals(tf_cpf.getText()) || "".equals(tf_paciente.getText()) || "".equals(tf_idade.getText())) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        } else {
            try {
                Paciente p = new Paciente(tf_cpf.getText(), tf_paciente.getText(), Integer.valueOf(tf_idade.getText()));
                PacienteDAO pacidao = new PacienteDAO();
                pacidao.save(p);
                
                JOptionPane.showMessageDialog(this, "Registro Inserido com Sucesso!");
                
                tf_cpf.setText("");
                tf_paciente.setText("");
                tf_idade.setText("");
            } catch (HeadlessException | NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Registro Duplicado!");
                e.printStackTrace();
            } finally {
                Object nomeColunas[] = {"CPF", "Paciente", "Idade"};
                DefaultTableModel model = new DefaultTableModel(nomeColunas, 0);
                PacienteDAO pacientedao = new PacienteDAO();
                for(Paciente p: pacientedao.getPacientes()) {
                    Object rowData[] = {p.getCpf(), p.getNome(), p.getIdade()};
                    model.addRow(rowData);
                }
                tab_pacientes.setModel(model);
            }
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
        String del_cpf;
        del_cpf = JOptionPane.showInputDialog("Qual é o CPF que deseja apagar?");
        
        try {
            PacienteDAO pacidao = new PacienteDAO();
            pacidao.removeById(del_cpf);
            JOptionPane.showMessageDialog(this, "Registro Excluído com sucesso!");
            
            tf_cpf.setText("");
            tf_paciente.setText("");
            tf_idade.setText("");
        } catch (Exception e) {
        } finally {
            Object nomeColunas[] = {"CPF", "Paciente", "Idade"};
            DefaultTableModel model = new DefaultTableModel(nomeColunas, 0);
            PacienteDAO pacientedao = new PacienteDAO();
            for(Paciente p: pacientedao.getPacientes()) {
                Object rowData[] = {p.getCpf(), p.getNome(), p.getIdade()};
                model.addRow(rowData);
            }
            tab_pacientes.setModel(model);
        }
        
        
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        jMenu1.setVisible(true);
        String cpf_base;
        String edit_cpf;
        String edit_paciente;
        String edit_idade;
        cpf_base = JOptionPane.showInputDialog("Qual é o CPF que deseja editar?");
        
        PacienteDAO pacidao = new PacienteDAO();
        
        try {
            List<Paciente> pBase = new ArrayList<>();
            pBase = pacidao.getPacientesLoked(cpf_base);
            //System.out.println(pBase.get(0).getCpf());
                       
            edit_cpf = JOptionPane.showInputDialog(this, "Novo CPF", pBase.get(0).getCpf());
            edit_paciente = JOptionPane.showInputDialog(this, "Novo Nome do Paciente", pBase.get(0).getNome());
            edit_idade = JOptionPane.showInputDialog(this, "Nova Idade", Integer.toString(pBase.get(0).getIdade()));
            
            Paciente pac = new Paciente(edit_cpf, edit_paciente, Integer.parseInt(edit_idade));
            
            pacidao.update(pac, cpf_base);
            
        } catch (Exception e) {
        } finally {
            Object nomeColunas[] = {"CPF", "Paciente", "Idade"};
            DefaultTableModel model = new DefaultTableModel(nomeColunas, 0);
            PacienteDAO pacientedao = new PacienteDAO();
            for(Paciente p: pacientedao.getPacientes()) {
                Object rowData[] = {p.getCpf(), p.getNome(), p.getIdade()};
                model.addRow(rowData);
            }
            tab_pacientes.setModel(model);
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacienteView().setVisible(true);
            }
        });
        
        // Populando tabela
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_background;
    private javax.swing.JTable tab_pacientes;
    private javax.swing.JTextField tf_cpf;
    private javax.swing.JTextField tf_idade;
    private javax.swing.JTextField tf_paciente;
    // End of variables declaration//GEN-END:variables
}